# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
