# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/
version: 2

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
