# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/helm-gcs/main.go
    binary: helm-gcs
    ldflags: -s -w -X github.com/nouney/helm-gcs/cmd/helm-gcs/cmd.version={{.Version}} -X github.com/nouney/helm-gcs/cmd/helm-gcs/cmd.commit={{.Commit}} -X github.com/nouney/helm-gcs/cmd/helm-gcs/cmd.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  format: tar.gz
  replacements:
    amd64: x86_64
    darwin: Darwin
    linux: Linux
