name: "gcs"
version: "0.4.3"
usage: "Chart repositories on Google Cloud Storage"
description: |-
  Manage repositories on Google Cloud Storage
command: "$HELM_PLUGIN_DIR/bin/helm-gcs"
downloaders:
- command: "scripts/pull.sh"
  protocols:
  - "gs"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
